### PR TITLE
Fix the 'logout' method

### PR DESCRIPTION
**Pull request by ghost**
It appears the endpoint no longer accepts a token payload, and now just takes
the token in the Authorization header.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Does it actually do anything (actually invalidate the token) yet?

**Comment by ghost** [comment]
To my knowledge, it does invalidate the token. I'll go and test this though. At the least, it'll no longer cause error exit codes to those that call the logout.

**Comment by ghost** [comment]
Looks like it doesn't, actually.

**Comment by SpaceManiac** [comment]
Did you test it on both bots and users? I would certainly expect nothing to happen for bots, but I wonder if the situation has changed for users.

**Comment by SpaceManiac** [comment]
In the long run I'll probably end up deleting this method, but for now if you rebase I'll merge.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
