### PR TITLE
Hyper 0.10 and openssl 0.9.

### PR DESCRIPTION
**Pull request by ArtemGr**
Some of the libraries I need are using openssl 0.9, so I've baked a version of discord-rs which works with the newer openssl-sys.

To untangle the older openssl I had to change the multipart code in `fn send_file`. Haven't tested it (my bot's not using that function yet) but it's based on something I use myself in another place.

Had to patch rust-websocket as well.

My bot's now working NP on the upgraded discord-rs so the patch got at least that bit of testing.

### CODE REVIEW

**Comment by bbigras** [comment]
Thanks for the patch. Do you think you change it to use native-tls? I think everyone is moving to that crate.

**Comment by iddm** [comment]
When this will be merged? I have waited for this too long already.

**Comment by ArtemGr** [comment]
@vityafx You can simply use my fork meanwhile, I'm merging upstream changes now and then. Just my two cents.

**Comment by SpaceManiac** [comment]
Crates.io does not accept git dependencies, so I can't accept this as-is. That said, I do really want to perform this update. What is the situation on `SslStream` not being cloneable anymore? Is there a workaround that doesn't involve forking rust-websocket?

I'm guessing Hyper has moved the TLS support out into this separate crate this version, and that's why it's necessary?

Also, I think newest multipart supports hyper 0.10, so it might be possible to avoid those changes.

**Comment by ArtemGr** [comment]
Hey, @SpaceManiac! I'll dive into your questions tomorrow.

**Comment by ArtemGr** [comment]
> Also, I think newest multipart supports hyper 0.10, so it might be possible to avoid those changes.

This dependency between dependencies (multipart and hyper) is a recipe for disaster. It's not the first time when multipart was lagging behind. I would argue that it's best to use the multipart crate without relying on its hyper support.

Should not be hard to reverse the multipart changes though.

> What is the situation on SslStream not being cloneable anymore?

Should no longer be a problem with the recent websocket. I guess here's the relevant commit:
https://github.com/cyderize/rust-websocket/commit/ebb11ebdb3c4e6c9b1f098e71338e2837939dd88

There was also some heavy refactoring:
https://github.com/cyderize/rust-websocket/commit/a6df89faf46aac64832c66ebc945f700d90f2f79

I'm not exactly familiar with this websocket library and how it's used in discord-rs so patching up discord-rs to support the revamped websocket architecture is above my paygrade. My guess would be that it is better for you to just bump the websocket version and start from scratch.

**Comment by SpaceManiac** [comment]
Thanks for investigating. I thought I might have to but I wanted to make sure you didn't have any tricks up your sleeve. I'll be looking at this shortly.

**Pull request closed without merging**
