### PR TITLE
Add helper methods for mentioning roles/users/channels

### PR DESCRIPTION
**Pull request by ghost**
Mentioning roles, users, and channels can be a bit ugly, as the syntax for each
is:
- channel: <#ID>
- role: <@&ID>
- user: @ID

These are helper methods on each struct to help prettify this a bit when
formatting strings.

There isn't really any precedence for helper functions like these, so I'm not sure if these are wanted.

An alternative implementation is to put these on the Ids (`ChannelId` etc.), so that this can be very easily used in scenarios like:

``` rust
# ...
Event::MessageCreate(message) => {
    # ...
    let text = format!("{}, please refer to the rules in {}",
                       message.user.id.mention(),
                       message.channel_id.mention());
    # ...
}
```

### CODE REVIEW

**Comment by ghost** [comment]
Actually there is already a precedent for this:

https://wombat.platymuus.com/rustdoc/discord_master/model/struct.Member.html#method.display_name

**Comment by iddm** [comment]
I have these functions implemented in my project. These functions are absolutely useful but you issed <@!USERID>

**Comment by ghost** [comment]
Committed the change under your name/email. You should register your email address with github so that it's properly attributed to you: https://github.com/settings/emails

**Comment by SpaceManiac** [comment]
Is there a difference in appearance in the client between standard and with-nickname mentions? I was under the impression they showed the same.

**Comment by ghost** [comment]
I think there used to be - that mentioning via `<@ID>` would display username rather than nick - but that doesn't appear to be correct anymore, and it now also shows the nick. Should I remove `mention_nickname`?

**Comment by SpaceManiac** [comment]
No point in having two methods that are functionally the same.

I'll look at some efficiency-related implementation details, and consider including the methods on IDs as well, when I have the chance.

**Comment by iddm** [comment]
You better test it. A nick name is equal to account name if you just joined the discord server. Nick names can be changed on each server so on one server you may have one nick, on another server - another nick. However, this mentions both highlight you, it may only depend on text in the mention - it may be a nick or a account name. I doubt they are showing the same - they are useless then. We should check it.

**Comment by ghost** [comment]
I just ran a test by nicknaming both a bot and a user, as well as myself. Doing both `<@ID>` and `<@!ID>` produced text to show showing the nickname on the desktop, mobile (android), and web versions. I've removed the `mention_nickname` function.

**Comment by iddm** [comment]
Well that gives a point to remove it but what if it is a bug of a client that will be fixed soon? If it is described in [official api](https://discordapp.com/developers/docs/resources/channel#message-formatting) then it should work then!

**Comment by ghost** [comment]
I asked Jake and here's what he said about it:

```
zey - Today at 10:33 PM
oh jake, sorry to bother you, but while we have your attention here, for the
discord-rs api library we've got an open PR for easily mentioning
users/channels/roles. it looks like right now mentioning via username <@> and
via nickname <@!> both produce the user's nickname. this appears to be on
desktop, web, and android, not sure about ios.

in the docs it's listed to not produce the same result:
https://discordapp.com/developers/docs/resources/channel#message-formatting

can you confirm if this is a bug or if it's now intended? is there someone else
I can ask that'd know?


Jake - Today at 10:52 PM
yes
that's right
<@!> is a hint
to tell the server to use a nickname in push notifs
it'll be removed soon
```

**Comment by iddm** [comment]
Nice. So now we can safely remove `mention_nickname`.

**Comment by SpaceManiac** [comment]
Thanks for the research work. I've gone with an alternate implementation in c8e4b55f84296e812ae0cb3ceb101a01cc6526fd.

**Pull request closed without merging**
