### PR TITLE
Implement @​me User IDs (fixes #136)

### LINKED ISSUE #136: No way to get a @me UserId?

### PR DESCRIPTION
**Pull request by jD91mZM2**

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Where else is `UserId(0)` already equivalent to `@me`? Or is this a proposed new feature? What's the usecase?

**Comment by jD91mZM2** [comment]
This is a proposed feature. ... Or workaround, really. Since we store user IDs as `u64`, there isn't much room for adding alternatives other than special-casing specific numbers.

Also check my response to #136.

**Comment by SpaceManiac** [comment]
What purpose does adding a representation for `@me` serve?

**Comment by jD91mZM2** [comment]
Lemme quote the reply on the other issue

> That returns the actual current user, not @​me. You can nickname @​me, but you can't nickname the current user id because of lacking permissions. Discord isn't smart enough

**Comment by jD91mZM2** [comment]
Plus it's cheaper to just use @​me and not look it up in state and stuffs

**Comment by jD91mZM2** [comment]
@SpaceManiac I just now noticed the delete_reactions function takes an `Option<UserId>`. Do you think that is a better solution? I could just change a few more functions to use that...

**Comment by SpaceManiac** [comment]
What endpoints have you been wanting to pass `@me` to? Have you confirmed it works?

**Comment by jD91mZM2** [comment]
In this case I am intending to use `@me` with the nick endpoint: https://discordapp.com/developers/docs/resources/guild#modify-current-user's-nick

Actually that wouldn't work just like that because of the extra /nick.... STILL, it's much cheaper to use `@me` than querying the current user ID if it would ever be required to use the current ID

**Comment by SpaceManiac** [comment]
Given that `@me` is not usable in all places a `UserId` is, and is only applicable on some endpoints, I think `Option<UserId>` might make more sense for those cases.

**Comment by jD91mZM2** [comment]
I guess I'm just thinking too low level haha

**Pull request closed without merging**
