### PR TITLE
The bot examples shouldn't try to logout

### PR DESCRIPTION
**Pull request by ghost**
Logging out errors for bots, so we shouldn't include it in the examples.

### CODE REVIEW

**Comment by TorstenCScholz** [comment]
I noticed this, too. But how do you "logout" with the bot? Doing nothings results in a timeout when the program exits.

**Comment by ghost** [comment]
@TorstenCScholz Use `connection.shutdown()`, it will remove your bot from the online list. After that, you can just let the program exit normally.

**Comment by SpaceManiac** [comment]
LGTM, just needs a rebase.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
