### PR TITLE
Decode discriminators as u16s instead of Strings

### LINKED ISSUE #40: Use numbers instead of strings for discriminators
The `0000` through `9999` range used for discriminators should fit comfortably in a u16. No need for a whole `String`.

### PR DESCRIPTION
**Pull request by ghost**
Closes #40.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I like it. One thing: could you continue to support I64 and U64 in `decode_discriminator`? I don't have a reference handy but I've occasionally seen some data inconsistencies and would like to handle those cases.

(Very minor cosmetic: "u16s" rather than "u16's" in the commit message)

**Comment by ghost** [comment]
Updated and rebased.

**Comment by SpaceManiac** [comment]
Just need a rebase and I'll merge.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
