### PR TITLE
[WIP] async gateway connections

### PR DESCRIPTION
**Pull request by tinaun**
continued from #143

### CODE REVIEW

**Comment by bdonlan** [comment]
FYI - I've been working on an async implementation of the `Connection` side of things, so it might be good to combine efforts. Currently I have it connecting, need to verify it stays connected over reconnections and need to add back in all the hooks for voice support and etc

**Comment by bdonlan** [comment]
I've posted my WIP over at https://github.com/SpaceManiac/discord-rs/pull/148

**Comment by jD91mZM2** [comment]
Should I close my pull request so we'll continue here?

**Comment by bdonlan** [comment]
They're somewhat independent so far in that changing out the http library for the request-response bits won't impact the async side too much. Doing the dependency update as a separate PR would therefore be worthwhile I think.

**Comment by tinaun** [comment]
im getting somewhere with this

**Comment by jD91mZM2** [comment]
Awesome! When do you plan on rebasing on top of the latest master? Leave it until you're done?

**Comment by tinaun** [comment]
yeah. im working on voice stuff now. its tricky! i may end up rewriting a lot more than just the network stuff. 

current todo list:

* parameterize gateways over the type of event they stream (`VoiceEvent` vs `GatewayEvent`) 
    * voice websocket streams are basically identical to regular gateway streams otherwise

* split the sync wrapper handle into the core event loop and a handle to a future, to allow concurrent gateway connections (voicegateway + gateway + voicedata at once) 

* write a stream + sink impl around tokios `UdpSocket` for the actual voice channel connections

* work out error handling - how should errors in channel sending be handled?

* handle reconnects in the sync `Connection` type

**Comment by jD91mZM2** [comment]
I adore your enthusiasm for the project :)

> how should errors in channel sending be handled?

You mean like `Sender.send`? That should probably just be unwrapped in the most cases, since it can only fail if the receiver is dropped, which it shouldn't be before the sender is.

**Comment by SpaceManiac** [comment]
Closing due to long-term WIP status and severe merge conflicts.

**Pull request closed without merging**
