### PR TITLE
Add server member retrieval function

### PR DESCRIPTION
**Pull request by ghost**
This is a continuation of #19 which I closed due to lack of time (at the time), but apparently can't reopen because I squashed my commits.

So I've been thinking this one over and I'm not sure how to implement the "get member list," depending on how you want it implemented.

It looks like this used to be retrievable over a simple REST endpoint, but it doesn't look like that's the case anymore.

As is my understanding, events would be coming in over time with the member list after calling `Connection::__download_members`, and these events would need to be used to update the state with. But, I'm not sure how this can be done, as this event-handling and calling on `state.update` is handled by the user and not the library, unlike e.g. discord.py which handles the state internally.

The way DiscordPHP handles this is just by returning whatever is already in the cache (state). Is this the way to go about this? If you have a pointer or two I can try to take another look if you want.

For now though, I've at least left in `get_member` to retrieve a single member from the API.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
There should be no `Discord::get_member_list`, because there is no longer a REST endpoint for it. The correct way to get a full member list is to connect to WS, initiate a list download, and wait for the user list to fill, as currently implemented. `get_member` is useful enough - but change to not take the IDs by reference.

**Comment by ghost** [comment]
Updated and squashed to 1 commit.

Okay, that's what I was thinking, thanks for the clarification. I was looking at issue #1 and noticed that there was still an unchecked `get member list` item and was thinking that `get_member_list` was still wanted as another way to do what you described.

**Comment by SpaceManiac** [comment]
Looks good; just needs a rebase.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
