### PR TITLE
Add function to get a single message by ID

### PR DESCRIPTION
**Pull request by valleyflowerbear**
Would `get_single_message` be more appropriate than `get_message` because of the potential confusion with `get_messages`?

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Instead of accepting `&ChannelId` and `&MessageId`, accept non-reference forms. I haven't got around to changing it on old ones, but new methods should not take IDs by reference. The name is fine.

**Comment by valleyflowerbear** [comment]
Done

**Comment by SpaceManiac** [comment]
If you can rebase this on top of current master, it's good to merge.

**Comment by valleyflowerbear** [comment]
Done

**Comment by SpaceManiac** [comment]
Merged in 8dbfcb1a93bebaa4d2998b88e5112cb1de5efc71

**Pull request closed without merging**
