### PR TITLE
Add new message pinning event + channel pin field

### LINKED ISSUE #41: New pinning-related fields
`PublicChannel` has new field `{"last_pin_timestamp":"2016-06-26T09:15:51.148000+00:00"}`.

New event `CHANNEL_PINS_UPDATE`: `{"channel_id": "194586744417550336", "last_pin_timestamp": "2016-07-11T22:30:01.152752+00:00"}`.

### PR DESCRIPTION
**Pull request by ghost**
This adds a new event for receiving channel pin updates (`CHANNEL_PINS_UPDATE`)
and a new fields for both `PrivateChannel`s and `PublicChannel`s,
`last_pin_timestamp`.

Updating the store with the event will update the relevant
{Public,Private}Channel's `last_pin_timestamp` field.

I am unsure on the implementation of the state update. Although the rest of the lib trends towards iterator chaining, I imagine this is a bit slower than a for-loop due to the `any` iter on top of the servers iter (due to a lack of the server id being provided), where a for-loop can be broken early, being at least a little more efficient. I haven't researched too much on Rust internally, so I'm not sure how optimized chaining is in comparison.

Closes #41.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I do use the iterator chaining elsewhere, mainly to keep things down to fewer lines, but in this case I think you'd be better served by structuring that piece of code similar to how the `find_channel` method is structured (iterating over `&mut` rather than `&` of course). You can then get away with an early return rather than a flag.

Everything else looks good.

**Comment by ghost** [comment]
Updated.

**Comment by SpaceManiac** [comment]
If you rebase, I'll merge.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
