### PR TITLE
Add server prune/prune count API functions

### PR DESCRIPTION
**Pull request by ghost**
Adds the following functions:
- begin_server_prune: `pub fn begin_server_prune(&self, server: &ServerId, days: u8) -> Result<ServerPrune>`
- get_server_prune_count: `pub fn get_server_prune_count(&self, server: &ServerId) -> Result<ServerPrune>`

The documentation for these endpoints can be found here:
https://discordapp.com/developers/docs/resources/guild#get-guild-prune-count

I don't have a Discord server to test this on myself but I assume this works. At the least, it states my server has 0 members to prune.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
- Use `ServerId` instead of `&ServerId`
- I haven't decided whether this type of range-checking should occur on the client side or whether it should be left to the server. No pressing need to change it yet, just a consideration.
- I'm not convinced the docs are correct regarding the possible days to prune. At the very least, the client's UI shows that it's possible to prune at 30 days. Maybe you should test and see at what day amount the server starts returning errors?

**Comment by ghost** [comment]
Updated to `ServerId`.

Looks like the docs [were wrong at the time](https://github.com/hammerandchisel/discord-api-docs/commit/d4c83bff9c970b4022636be66037cff22bb4aeed#diff-79f47ebc4b4a2e630dcf79e2a6638870R338) and recently updated, although it's not yet reflected on the website. I tested up to u64::MAX which does not error. Although I'm not sure why someone would need to delete that many days' worth. I can see a use case for pruning over 255 days' worth, so I've changed the type to u16.

In addition, since checking for the number of members that would be pruned accepts a `days` argument, I've added that in as an argument to `get_server_prune_count`.

**Comment by SpaceManiac** [comment]
- Missed `&ServerId` on get_server_prune_count.
- Does setting `days` to `0` cause the server to return an error? If so, the current check is fine; if not, and it just does nothing, I don't think there's a harm in omitting the check.
- `u16` seems fine.

**Comment by taiyaeix** [comment]
- Updated. Wow, can't believe I missed that
- indeed it does: `Err(Other("The number of days must at least be 1"))`

**Comment by ghost** [comment]
ignore my last comment, I'm trying to think too fast. =/
- updated.
- no, it does not: `Ok(ServerPrune { pruned: 0 })`

Removing the check.

**Comment by SpaceManiac** [comment]
Minor bikeshed - the docs are a little unclear. How about something like:
- Get the number of members who have been inactive for the specified number of days and would be pruned by a prune operation. Members with a role assigned will never be pruned.
- Start a prune operation, kicking members who have been inactive for the specified number of days. Members with a role assigned will never be pruned.

Also, the `pruned` field in `ServerPrune` needs to be `pub`, but I think that's it.

**Comment by ghost** [comment]
Agreed - updated and squashed to 1 commit.

**Pull request merged**
