### PR TITLE
Add bulk delete endpoint function

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Some notes:
- Accept `&[MessageId]` rather than `&Vec<MessageId>`
- `dedup` expects the vector to be sorted; either sort or don't dedup
- I'm currently deciding whether or not these client-side limit checks should be included; I'll let you know when I have a decision

**Comment by ghost** [comment]
Fixed bullet 1 and sorted the array prior to dedup'ing, thanks for the catch.

I can squash the commits down to 1 prior to merging once you make a decision on bullet 3

**Comment by SpaceManiac** [comment]
Three points:
- The "Errors" section in the docs is disproportionately large; I suggest folding the note about `Error::Other` being returned into the paragraph that states the 2-100 message limit.
- Should take a non-reference `ChannelId`.
- Minor nit, but I'd find it tidier if the second `ids.len()` check was an `else if`

Then, with a rebase, should be good to go.

**Comment by ghost** [comment]
Updated.

**Pull request merged**
