### PR TITLE
Add active/upcoming maintenance functions

### PR DESCRIPTION
**Pull request by ghost**
These two functions retrieve the active and upcoming status maintenances, respectively.

Now, this is rather difficult to test, because Discord right now is not having any maintenances and is not planning any maintenances. I tried looking for other companies that used statuspage.io, but couldn't find any that had active/scheduled.

So, I checked D4J's implementation and it looks like this should work, presuming that D4J's works:
https://github.com/austinv11/Discord4J/blob/6ffd7f797a9952285f53c87dade649076ab6c58c/src/main/java/sx/blah/discord/api/DiscordStatus.java#L70-L174

One part here that I'm not sure of is whether to have the base status URI as a static str.

I'll monitor Discord for the next few days to check if it's having issues so I can properly verify this works.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
`retry()` should be used instead of `self.request()`, because the status API endpoints do not require either the authorization or content-type headers to be attached. It might make sense to make these two functions free functions rather than members of `Discord` because they don't require logging in.

**Comment by ghost** [comment]
Updated. Can squash to 1 commit if everything looks good.

D4J also implements getting the API response time for day/week/month (https://github.com/austinv11/Discord4J/blob/6ffd7f797a9952285f53c87dade649076ab6c58c/src/main/java/sx/blah/discord/api/DiscordStatus.java#L24-L68). I'm not sure how useful these actually are, is this something that you'd be interested in being in the library? Seems like something that could just be implemented in userland if necessary.

**Comment by SpaceManiac** [comment]
Yeah, I don't mind leaving that to users, at least for the time being.

I notice a couple of `.clone()` calls - are those really needed?

**Comment by ghost** [comment]
I think they are. `decode_array` only accepts moved `serde_json::Value`'s, and Value isn't Copy-able.

**Comment by SpaceManiac** [comment]
Ah, I see - use `.remove()` instead of `.get()` to move the `Value`s out of the returned map.

**Comment by ghost** [comment]
Thanks; updated and squashed. Should be good to go now.

**Comment by SpaceManiac** [comment]
The fields on `Maintenance` need to be `pub` - but squash and rebase and it should be good.

**Comment by ghost** [comment]
Updated+squashed+rebased.

**Pull request merged**
