### PR TITLE
Add mfa_enabled parsing to CurrentUser

### PR DESCRIPTION
**Pull request by ghost**
The API now returns whether the user has two factor enabled on their account:

https://github.com/hammerandchisel/discord-api-docs/commit/c54a6d4f23f1093480f8c11df5f9b8132dd97d18

However, this is only sent for users, not for bots.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I'm pretty sure `.or(None)` is a no-op.

**Comment by SpaceManiac** [comment]
If it's not too long on the one line, it might be worth rewriting this match as an and_then. Otherwise, looks fine.

**Comment by ghost** [comment]
Fixed.

**Comment by SpaceManiac** [comment]
Have you observed mfa_enabled being absent in practice? It seems like it's present and false for bot accounts.

**Comment by ghost** [comment]
At the time it wasn't sending `mfa_enabled` for bots, but it looks like it is now. Updated.

**Comment by SpaceManiac** [comment]
Looks good, but needs rebase.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
