### PR TITLE
Support for building with Travis CI

### PR DESCRIPTION
**Pull request by jonalmeida**
Don't merge until you [enable Travis CI support][1] for the repository.

[1]: https://travis-ci.org/profile/

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
You need to install libsodium and also check `--no-default-features`.

**Comment by jonalmeida** [comment]
Ah yes, I'll try Travis out with my fork first and then I'll update this PR.

**Comment by jonalmeida** [comment]
Would it be wise to build the dependencies from source or install them via apt? It'll then limits builds to being only run on linux, but I'm not sure if that's something you'd want covered for CI. The alternative makes it easier to setup Travis using the [`APT`](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon) addon.

**Comment by jonalmeida** [comment]
I've updated my patch to install the dependencies using the APT plugin for now, and included building `libsodium` from source (the same way that ['sodiumoxide'](https://github.com/dnaq/sodiumoxide/blob/master/.travis.yml#L4) does it). 

[Here](https://travis-ci.org/jonalmeida/discord-rs/builds/173612025) is a green build from my fork for verification.

**Review by nabijaczleweli — APPROVED** [review]
Nice one :+1:

**Pull request closed without merging**
