### PR TITLE
Add method to get application info and owner

### PR DESCRIPTION
**Pull request by ghost**
Add a new method, `get_application_info`, to retrieve the information
about the current application as well as its owner.

This retrieves the following information:
- description
- flags
- icon
- id
- name
- rpc_origins
- owner info

The owner info consists of the owner account's:
- avatar
- discriminator
- id
- username

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Seems to me like `User` could be reused instead of `ApplicationOwner`. Just set `bot` = `false`.

**Comment by ghost** [comment]
Updated.

**Comment by SpaceManiac** [comment]
Looks good, tested too, just needs a rebase.

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
