### PR TITLE
Make ReadState's 'mention_count' default to 0

### PR DESCRIPTION
**Pull request by ghost**
The `mention_count` on ReadState is no longer being sent, and was causing this
error on connection for users (bots are fine):

```
thread '<main>' panicked at 'connect failed: Decode("Unexpected absent key", "mention_count")', ../src/libcore/result.rs:785
```

However, all of ReadState was deprecated a while ago:

https://github.com/hammerandchisel/discord-api-docs/commit/735ace8a11a31ee51761eeb9d9812970cf6c1f96

Considering the rest of ReadState now only contains:
- `id`: the relevant channel id; and
- `last_message_id`: the last message id ack'd on the channel

which are both given in the Channel object, I think removing it completely would
eventually be needed and may as well be done now.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
As far as I can tell, the deprecation applies only to bot accounts. Is there any further suggestion that ReadState is disappearing for users?

**Comment by ghost** [comment]
The relevant issue from the commit does say it's only removed for bots, although it's a couple months old, so perhaps out-dated. To answer your question: not that I can find, no. The only "hint" towards this still being supported is that the only other libraries referencing read_state currently are discord.net and discordgo.

I'll ask around.

**Comment by ghost** [comment]
```
⎛⎝xX_jake_Xx⎠⎞ - Today at 8:02 PM
@zey for user accts. mention_count isnt sent if it's zero.
```

I've updated the PR to make the field optional. Would you rather it simply default to 0?

**Comment by ghost** [comment]
I changed it to default to 0 instead of being optional, it makes more sense even if it's not an absolutely accurate representation of what the API is sending.

**Pull request merged**
