### PR TITLE
Fix the logout method again

### LINKED ISSUE #62: Logout unauthorized
so when I try to call
`client.logout().expect("logout failed");`

I get this for some reason
`thread '<main>' panicked at 'logout failed: Status(Unauthorized, Some({"code":0,"message":"401: Unauthorized"}))', src/libcore/result.rs:785`

I am playing with one of the example projects but I changed the login to use `Discord::new_cache` so I could pass in my login details.

could this have broken it?

### PR DESCRIPTION
**Pull request by ghost**
The logout method has changed to requiring two null fields (`provider`
and `token`) to successfully POST.

The method still does not do anything, but this will probably change in
the future.

Closes #62.

/cc @tastytentacles although the method still doesn't do anything, it _might/probably will_ at some point in the future as they've been changing it around lately

### CODE REVIEW

**Comment by tastytentacles** [comment]
Ok, thank you.
so just let my client time out? I mean that works fine just hoping there was a more elegant solution.

**Comment by ghost** [comment]
If you have a [Connection](https://wombat.platymuus.com/rustdoc/discord_master/struct.Connection.html) open, you can call [`connection.shutdown()`](https://wombat.platymuus.com/rustdoc/discord_master/struct.Connection.html#method.shutdown) and it should remove you/your bot from the online users list, rather than waiting the few minutes for it to update as being offline.

This change is not yet released in a new version though; `connection.shutdown()` doesn't do this on v0.6.0, so if you track via git you will have this change.

In your Cargo.toml:

``` toml
[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
```

**Comment by tastytentacles** [comment]
I am having some trouble building from the git version, when I have a bit more time I will give it another go. thank you for all the help :+1:

**Comment by ghost** [comment]
Try a `cargo update` and then try building again.

If you have any more issues or questions we're at the #rust_discord-rs channel in the [Discord API server](https://discord.gg/0SBTUU1wZTWAPisK) 👍

**Pull request merged**
